# Generated by Django 3.0.6 on 2020-06-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_selector', 'first_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category'},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name': 'fooditem'},
        ),
    ]
